### ISSUE TITLE
exports only part of the path

### ISSUE THREAD

**Issue by isladjan** [baronwatts/blender-curve-coordinate-points#1]
I have a closed path consisting of 5 bezier path. When I export this path and recreate it in Three.js, only part is visible.
I used this tutorial - [Link](https://baronwatts.com/exporting-a-curve-from-blender-to-three-js/) for recreate path in Three.js

![1](https://user-images.githubusercontent.com/26748614/126959608-7a2c6ee2-7b50-46e1-8688-cb4a422c76ba.png)
![2](https://user-images.githubusercontent.com/26748614/126959611-e714076c-7999-4b74-bdbc-71e4bcbac78a.png)
![3](https://user-images.githubusercontent.com/26748614/126959605-1fd94e38-82a1-4355-9fb6-bc536367c78a.png)

**Comment by baronwatts** [comment]
Try setting the close method to true and see if that works. Here is the link to help:
http://www.nightloader.org/code/nightloader/asset/three/docs/api/extras/curves/CatmullRomCurve3.html

**Comment by isladjan** [comment]
> Try setting the close method to true and see if that works. Here is the link to help:
> http://www.nightloader.org/code/nightloader/asset/three/docs/api/extras/curves/CatmullRomCurve3.html

thank you

**Comment by baronwatts** [comment]
No problemo 👍🏾
